import os
from enum import Enum
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
TEMPLATES_DIR = BASE_DIR / "templates"
CHARACTERS_FILE = DATA_DIR / "characters.json"
FOODS_FILE = DATA_DIR / "foods.json"
ANSWER_PATTERNS_FILE = DATA_DIR / "answer_patterns.json"
CHATBOT_ID = "Mexico"
LESSON_TYPE = "LIKE"

class Stage(str, Enum):
    WAIT_GREETING = "WAIT_GREETING"
    WAIT_FEELING = "WAIT_FEELING"
    STUDENT_QUESTION_1 = "STUDENT_QUESTION_1"
    STUDENT_QUESTION_2 = "STUDENT_QUESTION_2"
    STUDENT_PREFERENCE = "STUDENT_PREFERENCE"
    STUDENT_QUESTION_3 = "STUDENT_QUESTION_3"
    COUNTRY_PREFERENCE = "COUNTRY_PREFERENCE"
    END = "END"

INITIAL_STAGE = Stage.WAIT_GREETING
MAX_HISTORY_MESSAGES = 30
MODEL_NAME = "gpt-4o-mini"
TEMPERATURE = 0.3
MAX_RESPONSE_TOKENS = 80
OPENAI_API_KEY_ENV = "OPENAI_API_KEY"
ENABLE_GOOGLE_SHEETS = True
SPREADSHEET_ID = "1D1xcyBiIOtBE3QfrPMx84RVIREf-8kq5XDqTZWCrDMU"
GOOGLE_SERVICE_ACCOUNT_ENV = "GOOGLE_SERVICE_ACCOUNT"
FLASK_SECRET_KEY = os.environ.get("FLASK_SECRET_KEY", "mexico-like-chatbot-secret-key")
